version: "3.9"

services:
  backend:
    build: ./backend
    container_name: hostel-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend/db:/app/db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: hostel-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    restart: always